# Generated by Django 6.0.4 on 2026-04-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_milestone_milestonepayment'),
    ]

    operations = [
    ]
