# Generated by Copilot-style patch: add position and default milestones
from django.db import migrations, models


def create_default_milestones(apps, schema_editor):
    Milestone = apps.get_model('payments', 'Milestone')
    defaults = [
        ('basic', 1, 'Basic Milestone 1', '10.00'),
        ('basic', 2, 'Basic Milestone 2', '20.00'),
        ('basic', 3, 'Basic Milestone 3', '30.00'),
        ('standard', 1, 'Standard Milestone 1', '50.00'),
        ('standard', 2, 'Standard Milestone 2', '100.00'),
        ('standard', 3, 'Standard Milestone 3', '150.00'),
        ('premium', 1, 'Premium Milestone 1', '200.00'),
        ('premium', 2, 'Premium Milestone 2', '400.00'),
        ('premium', 3, 'Premium Milestone 3', '800.00'),
    ]
    for tier, position, name, amount in defaults:
        Milestone.objects.update_or_create(
            tier=tier,
            position=position,
            defaults={'name': name, 'amount': amount}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_create_default_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=['tier', 'position'], name='unique_tier_position'),
        ),
        migrations.RunPython(create_default_milestones, reverse_code=migrations.RunPython.noop),
    ]
