# Generated by Django 6.0.4 on 2026-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_three_milestones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
